const data = [
    {
        img: "https://m.media-amazon.com/images/I/51UhwaQXCpL._AC_UL320_.jpg",
        title: "Oneplus Bullets Z2 Bluetooth Wireless in Ear Earphones with Mic",
        star: 2,
        reviews: "(123 reviews)",
        prevPrice: "140,00",
        newPrice: "200",
        company: "oneplus",
        color: "black",
        category: "earbuds",
    },
    {
        img: "https://m.media-amazon.com/images/I/51UhwaQXCpL._AC_UL320_.jpg",
        title: "Samsung Galaxy Buds Pro",
        star: 4,
        reviews: "(500 reviews)",
        prevPrice: "200,00",
        newPrice: "250",
        company: "Samsung",
        color: "white",
        category: "earbuds",
    },
    {
        img: "https://m.media-amazon.com/images/I/51UhwaQXCpL._AC_UL320_.jpg",
        title: "Samsung Galaxy Buds2",
        star: 4,
        reviews: "(300 reviews)",
        prevPrice: "150,00",
        newPrice: "200",
        company: "Samsung",
        color: "black",
        category: "earbuds",
    },
    {
        img: "https://m.media-amazon.com/images/I/51UhwaQXCpL._AC_UL320_.jpg",
        title: "Apple AirPods Pro",
        star: 4,
        reviews: "(1000 reviews)",
        prevPrice: "250,00",
        newPrice: "300",
        company: "Apple",
        color: "white",
        category: "earbuds",
    },
    {
        img: "https://m.media-amazon.com/images/I/51UhwaQXCpL._AC_UL320_.jpg",
        title: "Apple AirPods",
        star: 4,
        reviews: "(500 reviews)",
        prevPrice: "150,00",
        newPrice: "200",
        company: "Apple",
        color: "white",
        category: "earbuds",
    },
    {
        img: "https://m.media-amazon.com/images/I/51UhwaQXCpL._AC_UL320_.jpg",
        title: "OnePlus Bullets Wireless Z",
        star: 4,
        reviews: "(200 reviews)",
        prevPrice: "100,00",
        newPrice: "150",
        company: "oneplus",
        color: "black",
        category: "earbuds",
    },
    {
        img: "https://m.media-amazon.com/images/I/51UhwaQXCpL._AC_UL320_.jpg",
        title: "OnePlus Bullets Wireless",
        star: 4,
        reviews: "(100 reviews)",
        prevPrice: "80,00",
        newPrice: "120",
        company: "oneplus",
        color: "black",
        category: "earbuds",
    },
    {
        img: "https://m.media-amazon.com/images/I/51UhwaQXCpL._AC_UL320_.jpg",
        title: "boAt Rockerz 450 Bluetooth Headphone",
        star: 4,
        reviews: "(1000 reviews)",
        prevPrice: "200,00",
        newPrice: "250",
        company: "boAt",
        color: "black",
        category: "headphones",
    },
    {
        img: "https://m.media-amazon.com/images/I/51UhwaQXCpL._AC_UL320_.jpg",
        title: "boAt Rockerz 350 Bluetooth Headphone",
        star: 4,
        reviews: "(500 reviews)",
        prevPrice: "150,00",
        newPrice: "200",
        company: "boAt",
        color: "black",
        category: "headphones",
    },
    {
        img: "https://m.media-amazon.com/images/I/51UhwaQXCpL._AC_UL320_.jpg",
        title: "iQOO Neo 6 5G",
        star: 4,
        reviews: "(200 reviews)",
        prevPrice: "300,00",
        newPrice: "350",
        company: "iQOO",
        color: "black",
        category: "smartphones",
    },
    {
        img: "https://m.media-amazon.com/images/I/51UhwaQXCpL._AC_UL320_.jpg",
        title: "Sony WH-1000XM5 Wireless Noise Cancelling Headphones",
        star: 4,
        reviews: "(500 reviews)",
        prevPrice: "350,00",
        newPrice: "400",
        company: "Sony",
        color: "black",
        category: "headphones",
    },
    {
        img: "https://m.media-amazon.com/images/I/51UhwaQXCpL._AC_UL320_.jpg",
        title: "realme Buds Air 3",
        star: 4,
        reviews: "(100 reviews)",
        prevPrice: "50,00",
        newPrice: "70",
        company: "realme",
        color: "white",
        category: "earbuds",
    },
    {
        img: "https://m.media-amazon.com/images/I/51UhwaQXCpL._AC_UL320_.jpg",
        title: "JBL C100SI Wired Earphones",
        star: 4,
        reviews: "(500 reviews)",
        prevPrice: "30,00",
        newPrice: "50",
        company: "JBL",
        color: "black",
        category: "earphones",
    },
    {
        img: "https://m.media-amazon.com/images/I/51UhwaQXCpL._AC_UL320_.jpg",
        title: "Redmi Earbuds S",
        star: 4,
        reviews: "(200 reviews)",
        prevPrice: "40,00",
        newPrice: "60",
        company: "Redmi",
        color: "black",
        category: "earbuds",
    },
    {
        img: "https://m.media-amazon.com/images/I/51UhwaQXCpL._AC_UL320_.jpg",
        title: "HP Pavilion Gaming 15.6-inch Laptop",
        star: 4,
        reviews: "(100 reviews)",
        prevPrice: "800,00",
        newPrice: "900",
        company: "HP",
        color: "black",
        category: "laptops",
    },
    {
        img: "https://m.media-amazon.com/images/I/51UhwaQXCpL._AC_UL320_.jpg",
        title: "Samsung Galaxy Watch4",
        star: 4,
        reviews: "(200 reviews)",
        prevPrice: "200,00",
        newPrice: "250",
        company: "Samsung",
        color: "black",
        category: "smartwatches",
    },
    {
        img: "https://m.media-amazon.com/images/I/51UhwaQXCpL._AC_UL320_.jpg",
        title: "Apple iPad (9th Generation)",
        star: 4,
        reviews: "(500 reviews)",
        prevPrice: "300,00",
        newPrice: "350",
        company: "Apple",
        color: "space gray",
        category: "tablets",
    },
    {
        img: "https://m.media-amazon.com/images/I/51UhwaQXCpL._AC_UL320_.jpg",
        title: "OnePlus Nord 2 5G",
        star: 4,
        reviews: "(200 reviews)",
        prevPrice: "300,00",
        newPrice: "350",
        company: "oneplus",
        color: "gray",
        category: "smartphones",
    },
    {
        img: "https://m.media-amazon.com/images/I/51UhwaQXCpL._AC_UL320_.jpg",
        title: "Sony PlayStation 5",
        star: 4,
        reviews: "(1000 reviews)",
        prevPrice: "500,00",
        newPrice: "550",
        company: "Sony",
        color: "white",
        category: "gaming consoles",
    },
    {
        img: "https://m.media-amazon.com/images/I/51UhwaQXCpL._AC_UL320_.jpg",
        title: "Philips Trimmer Cordless QT4000/15",
        star: 4,
        reviews: "(100 reviews)",
        prevPrice: "150,00",
        newPrice: "180",
        company: "Philips",
        color: "black",
        category: "grooming",
    },
    {
        img: "https://m.media-amazon.com/images/I/51UhwaQXCpL._AC_UL320_.jpg",
        title: "Havells Opal ET 15 Litre Instant Geyser",
        star: 4,
        reviews: "(50 reviews)",
        prevPrice: "400,00",
        newPrice: "450",
        company: "Havells",
        color: "white",
        category: "home appliances",
    },
    {
        img: "https://m.media-amazon.com/images/I/51UhwaQXCpL._AC_UL320_.jpg",
        title: "Eureka Forbes Aquasure from Aquaguard Smart 20-Watt UV Water Purifier",
        star: 4,
        reviews: "(100 reviews)",
        prevPrice: "250,00",
        newPrice: "300",
        company: "Eureka Forbes",
        color: "white",
        category: "home appliances",
    },
    {
        img: "https://m.media-amazon.com/images/I/51UhwaQXCpL._AC_UL320_.jpg",
        title: "Butterfly Rapid 4 Jar Mixer Grinder, 1100W",
        star: 4,
        reviews: "(50 reviews)",
        prevPrice: "250,00",
        newPrice: "300",
        company: "Butterfly",
        color: "white",
        category: "kitchen appliances",
    },
    {
        img: "https://m.media-amazon.com/images/I/51UhwaQXCpL._AC_UL320_.jpg",
        title: "Prestige IRIS 750 Watt Mixer Grinder",
        star: 4,
        reviews: "(100 reviews)",
        prevPrice: "200,00",
        newPrice: "250",
        company: "Prestige",
        color: "white",
        category: "kitchen appliances",
    },
    {
        img: "https://m.media-amazon.com/images/I/51UhwaQXCpL._AC_UL320_.jpg",
        title: "Godrej 236 L 2 Star Double Door Refrigerator",
        star: 4,
        reviews: "(20 reviews)",
        prevPrice: "1500,00",
        newPrice: "1700",
        company: "Godrej",
        color: "silver",
        category: "refrigerators",
    },
    {
        img: "https://m.media-amazon.com/images/I/51UhwaQXCpL._AC_UL320_.jpg",
        title: "Whirlpool 265 L 3 Star Double Door Refrigerator",
        star: 4,
        reviews: "(30 reviews)",
        prevPrice: "2000,00",
        newPrice: "2200",
        company: "Whirlpool",
        color: "steel",
        category: "refrigerators",
    },
    {
        img: "https://m.media-amazon.com/images/I/51UhwaQXCpL._AC_UL320_.jpg",
        title: "LG 32 L Convection Microwave Oven",
        star: 4,
        reviews: "(20 reviews)",
        prevPrice: "800,00",
        newPrice: "900",
        company: "LG",
        color: "black",
        category: "microwave ovens",
    },
    {
        img: "https://m.media-amazon.com/images/I/51UhwaQXCpL._AC_UL320_.jpg",
        title: "IFB 25 L Convection Microwave Oven",
        star: 4,
        reviews: "(15 reviews)",
        prevPrice: "600,00",
        newPrice: "700",
        company: "IFB",
        color: "white",
        category: "microwave ovens",
    },
    {
        img: "https://m.media-amazon.com/images/I/51UhwaQXCpL._AC_UL320_.jpg",
        title: "Bajaj Majesty DX 11 1000-Watt Dry Iron",
        star: 4,
        reviews: "(50 reviews)",
        prevPrice: "500,00",
        newPrice: "550",
        company: "Bajaj",
        color: "white",
        category: "home appliances",
    },
    {
        img: "https://m.media-amazon.com/images/I/51UhwaQXCpL._AC_UL320_.jpg",
        title: "Usha Powerglow 3600 Watt Room Heater",
        star: 4,
        reviews: "(20 reviews)",
        prevPrice: "800,00",
        newPrice: "900",
        company: "Usha",
        color: "white",
        category: "heaters",
    },
    {
        img: "https://m.media-amazon.com/images/I/51UhwaQXCpL._AC_UL320_.jpg",
        title: "Havells Monza 1200mm Ceiling Fan",
        star: 4,
        reviews: "(30 reviews)",
        prevPrice: "1200,00",
        newPrice: "1400",
        company: "Havells",
        color: "brown",
        category: "ceiling fans",
    },
    {
        img: "https://m.media-amazon.com/images/I/51UhwaQXCpL._AC_UL320_.jpg",
        title: "Crompton Greaves Aura 1200mm Ceiling Fan",
        star: 4,
        reviews: "(20 reviews)",
        prevPrice: "1000,00",
        newPrice: "1200",
        company: "Crompton Greaves",
        color: "white",
        category: "ceiling fans",
    },
    {
        img: "https://m.media-amazon.com/images/I/51UhwaQXCpL._AC_UL320_.jpg",
        title: "Philips Airfryer Avance XXL",
        star: 4,
        reviews: "(50 reviews)",
        prevPrice: "1500,00",
        newPrice: "1700",
        company: "Philips",
        color: "black",
        category: "kitchen appliances",
    },
    {
        img: "https://m.media-amazon.com/images/I/51UhwaQXCpL._AC_UL320_.jpg",
        title: "Preethi Zodiac MG 218 750-Watt Mixer Grinder",
        star: 4,
        reviews: "(30 reviews)",
        prevPrice: "800,00",
        newPrice: "900",
        company: "Preethi",
        color: "white",
        category: "kitchen appliances",
    },
    {
        img: "https://m.media-amazon.com/images/I/51UhwaQXCpL._AC_UL320_.jpg",
        title: "Bosch Truemixx Pro 1000-Watt Mixer Grinder",
        star: 4,
        reviews: "(20 reviews)",
        prevPrice: "1200,00",
        newPrice: "1400",
        company: "Bosch",
        color: "white",
        category: "kitchen appliances",
    },
    {
        img: "https://m.media-amazon.com/images/I/51UhwaQXCpL._AC_UL320_.jpg",
        title: "Godrej 190 L 5 Star Direct Cool Single Door Refrigerator",
        star: 4,
        reviews: "(15 reviews)",
        prevPrice: "1500,00",
        newPrice: "1700",
        company: "Godrej",
        color: "silver",
        category: "refrigerators",
    },
    {
        img: "https://m.media-amazon.com/images/I/51UhwaQXCpL._AC_UL320_.jpg",
        title: "Whirlpool 340 L 3 Star Frost-Free Double Door Refrigerator",
        star: 4,
        reviews: "(20 reviews)",
        prevPrice: "2500,00",
        newPrice: "2800",
        company: "Whirlpool",
        color: "steel",
        category: "refrigerators",
    },
    {
        img: "https://m.media-amazon.com/images/I/51UhwaQXCpL._AC_UL320_.jpg",
        title: "Voltas 1.5 Ton 5 Star Inverter Split AC",
        star: 4,
        reviews: "(20 reviews)",
        prevPrice: "3500,00",
        newPrice: "3800",
        company: "Voltas",
        color: "white",
        category: "air conditioners",
    },
    {
        img: "https://m.media-amazon.com/images/I/51UhwaQXCpL._AC_UL320_.jpg",
        title: "Daikin 1.5 Ton 5 Star Inverter Split AC",
        star: 4,
        reviews: "(15 reviews)",
        prevPrice: "4000,00",
        newPrice: "4300",
        company: "Daikin",
        color: "white",
        category: "air conditioners",
    },
    {
        img: "https://m.media-amazon.com/images/I/51UhwaQXCpL._AC_UL320_.jpg",
        title: "Blue Star 1.5 Ton 5 Star Inverter Split AC",
        star: 4,
        reviews: "(10 reviews)",
        prevPrice: "4500,00",
        newPrice: "4800",
        company: "Blue Star",
        color: "white",
        category: "air conditioners",
    },
    {
        img: "https://m.media-amazon.com/images/I/51UhwaQXCpL._AC_UL320_.jpg",
        title: "Onida 80 cm (32 inches) HD Ready LED TV",
        star: 4,
        reviews: "(20 reviews)",
        prevPrice: "1500,00",
        newPrice: "1800",
        company: "Onida",
        color: "black",
        category: "televisions",
    },
    {
        img: "https://m.media-amazon.com/images/I/51UhwaQXCpL._AC_UL320_.jpg",
        title: "TCL 108 cm (43 inches) Full HD LED TV",
        star: 4,
        reviews: "(15 reviews)",
        prevPrice: "2500,00",
        newPrice: "2800",
        company: "TCL",
        color: "black",
        category: "televisions",
    },
    {
        img: "https://m.media-amazon.com/images/I/51UhwaQXCpL._AC_UL320_.jpg",
        title: "Mi 4A Horizon Edition 80 cm (32 inches) HD Ready LED TV",
        star: 4,
        reviews: "(10 reviews)",
        prevPrice: "2000,00",
        newPrice: "2300",
        company: "Mi",
        color: "black",
        category: "televisions",
    },
    {
        img: "https://m.media-amazon.com/images/I/51UhwaQXCpL._AC_UL320_.jpg",
        title: "Samsung 6.2 kg Fully Automatic Top Load Washing Machine",
        star: 4,
        reviews: "(20 reviews)",
        prevPrice: "2500,00",
        newPrice: "2800",
        company: "Samsung",
        color: "white",
        category: "washing machines",
    },
    {
        img: "https://m.media-amazon.com/images/I/51UhwaQXCpL._AC_UL320_.jpg",
        title: "LG 6.5 kg Fully Automatic Top Load Washing Machine",
        star: 4,
        reviews: "(15 reviews)",
        prevPrice: "2800,00",
        newPrice: "3100",
        company: "LG",
        color: "white",
        category: "washing machines",
    },
    {
        img: "https://m.media-amazon.com/images/I/51UhwaQXCpL._AC_UL320_.jpg",
        title: "Whirlpool 7 kg Fully Automatic Top Load Washing Machine",
        star: 4,
        reviews: "(10 reviews)",
        prevPrice: "3200,00",
        newPrice: "3500",
        company: "Whirlpool",
        color: "white",
        category: "washing machines",
    },
];


export default data;