const data = [
  {
    id: "product-qwnbqwskjawbkjbqw",
    img: "https://images.unsplash.com/photo-1640465978467-fa011a5dfb0a",
    title: "Levi's Women's Slim Fit Stretch Jeans",
    star: 5,
    reviews: "(4,520 reviews)",
    prevPrice: "89.99",
    newPrice: "59.99",
    company: "Levi's",
    color: "blue",
    category: "jeans",
    size: ["S", "M", "L", "XL", "XXL"],
    material: "Cotton Blend",
    gender: "men",
    style: "casual",
    availability: "in stock",
    description:
      "These Levi's Men's Slim Fit Stretch Jeans are designed for ultimate comfort and a stylish, modern look. Made from a high-quality cotton blend with a touch of elastane for added stretch, they provide the perfect balance of durability and flexibility. The classic 5-pocket design offers practicality, while the slim fit ensures a sleek silhouette. These jeans are perfect for both casual outings and more dressy occasions, making them a versatile addition to any wardrobe.",
    features: [
      "Stretchable fabric for comfort and flexibility",
      "Classic 5-pocket design for practicality",
      "Slim fit cut for a sleek, modern silhouette",
      "Machine washable for easy care",
      "Available in multiple sizes for the perfect fit",
    ],
    tags: [
      "slim fit",
      "denim",
      "casual wear",
      "trendy",
      "stretchable",
      "comfortable",
      "modern",
    ],
    sku: "LV-001-SFJ-BLU",
    shipping: {
      type: "standard",
      duration: "3-5 business days",
      cost: "free",
      international: {
        available: true,
        cost: "variable",
        duration: "7-15 business days",
      },
    },
    returnPolicy: {
      duration: "30 days",
      condition: "Unworn with tags, original packaging",
    },
    ratingsBreakdown: {
      5: 3200,
      4: 900,
      3: 250,
      2: 100,
      1: 70,
    },
    season: ["spring", "fall", "winter"],
    origin: "Made in Bangladesh",
    careInstructions: [
      "Machine wash cold",
      "Do not bleach",
      "Tumble dry low",
      "Warm iron if needed",
    ],
    modelWearing: {
      height: "6'1\"",
      size: "M",
    },
    fit: "slim",
    waistRise: "mid-rise",
    lengthOptions: ["30", "32", "34"],
    sustainability: {
      ecoFriendlyDyes: true,
      waterSavingTechnology: true,
      recyclablePackaging: true,
    },
    relatedProducts: [
      "Levi's Men's Graphic T-Shirt",
      "Levi's Denim Jacket",
      "Levi's Leather Belt",
    ],
    wishlistEnabled: true,
    inCart: false,
    discountPercent: 33,
    productUrl: "https://www.amazon.com/dp/B08JY3YP5G",
    brandUrl: "https://www.levi.com",
    customerQuestions: [
      {
        question: "Are these jeans true to size?",
        answer:
          "Yes, these jeans fit true to size. If you're between sizes, we recommend going up to the next size for a more comfortable fit.",
      },
      {
        question: "Can I machine wash these jeans?",
        answer:
          "Yes, these jeans are machine washable. Just follow the care instructions for the best results.",
      },
    ],
    availabilityStatus: {
      stockLevel: 320,
      restockDate: "2025-05-15",
    },
  },
  {
    id: "product-qwnbqwskjawbkjbqw1",
    img: "https://images.unsplash.com/photo-1640465978467-fa011a5dfb0a",
    title: "Levi's Women's Slim Fit Stretch Jeans",
    star: 5,
    reviews: "(4,520 reviews)",
    prevPrice: "89.99",
    newPrice: "59.99",
    company: "Levi's",
    color: "blue",
    category: "jeans",
    size: ["S", "M", "L", "XL", "XXL"],
    material: "Cotton Blend",
    gender: "men",
    style: "casual",
    availability: "in stock",
    description:
      "These Levi's Men's Slim Fit Stretch Jeans are designed for ultimate comfort and a stylish, modern look. Made from a high-quality cotton blend with a touch of elastane for added stretch, they provide the perfect balance of durability and flexibility. The classic 5-pocket design offers practicality, while the slim fit ensures a sleek silhouette. These jeans are perfect for both casual outings and more dressy occasions, making them a versatile addition to any wardrobe.",
    features: [
      "Stretchable fabric for comfort and flexibility",
      "Classic 5-pocket design for practicality",
      "Slim fit cut for a sleek, modern silhouette",
      "Machine washable for easy care",
      "Available in multiple sizes for the perfect fit",
    ],
    tags: [
      "slim fit",
      "denim",
      "casual wear",
      "trendy",
      "stretchable",
      "comfortable",
      "modern",
    ],
    sku: "LV-001-SFJ-BLU",
    shipping: {
      type: "standard",
      duration: "3-5 business days",
      cost: "free",
      international: {
        available: true,
        cost: "variable",
        duration: "7-15 business days",
      },
    },
    returnPolicy: {
      duration: "30 days",
      condition: "Unworn with tags, original packaging",
    },
    ratingsBreakdown: {
      5: 3200,
      4: 900,
      3: 250,
      2: 100,
      1: 70,
    },
    season: ["spring", "fall", "winter"],
    origin: "Made in Bangladesh",
    careInstructions: [
      "Machine wash cold",
      "Do not bleach",
      "Tumble dry low",
      "Warm iron if needed",
    ],
    modelWearing: {
      height: "6'1\"",
      size: "M",
    },
    fit: "slim",
    waistRise: "mid-rise",
    lengthOptions: ["30", "32", "34"],
    sustainability: {
      ecoFriendlyDyes: true,
      waterSavingTechnology: true,
      recyclablePackaging: true,
    },
    relatedProducts: [
      "Levi's Men's Graphic T-Shirt",
      "Levi's Denim Jacket",
      "Levi's Leather Belt",
    ],
    wishlistEnabled: true,
    inCart: false,
    discountPercent: 33,
    productUrl: "https://www.amazon.com/dp/B08JY3YP5G",
    brandUrl: "https://www.levi.com",
    customerQuestions: [
      {
        question: "Are these jeans true to size?",
        answer:
          "Yes, these jeans fit true to size. If you're between sizes, we recommend going up to the next size for a more comfortable fit.",
      },
      {
        question: "Can I machine wash these jeans?",
        answer:
          "Yes, these jeans are machine washable. Just follow the care instructions for the best results.",
      },
    ],
    availabilityStatus: {
      stockLevel: 320,
      restockDate: "2025-05-15",
    },
  },
  {
    id: "product-qwnbqwskjawbkjbqw2",
    img: "https://images.unsplash.com/photo-1640465978467-fa011a5dfb0a",
    title: "Levi's Women's Slim Fit Stretch Jeans",
    star: 5,
    reviews: "(4,520 reviews)",
    prevPrice: "89.99",
    newPrice: "59.99",
    company: "Levi's",
    color: "blue",
    category: "jeans",
    size: ["S", "M", "L", "XL", "XXL"],
    material: "Cotton Blend",
    gender: "men",
    style: "casual",
    availability: "in stock",
    description:
      "These Levi's Men's Slim Fit Stretch Jeans are designed for ultimate comfort and a stylish, modern look. Made from a high-quality cotton blend with a touch of elastane for added stretch, they provide the perfect balance of durability and flexibility. The classic 5-pocket design offers practicality, while the slim fit ensures a sleek silhouette. These jeans are perfect for both casual outings and more dressy occasions, making them a versatile addition to any wardrobe.",
    features: [
      "Stretchable fabric for comfort and flexibility",
      "Classic 5-pocket design for practicality",
      "Slim fit cut for a sleek, modern silhouette",
      "Machine washable for easy care",
      "Available in multiple sizes for the perfect fit",
    ],
    tags: [
      "slim fit",
      "denim",
      "casual wear",
      "trendy",
      "stretchable",
      "comfortable",
      "modern",
    ],
    sku: "LV-001-SFJ-BLU",
    shipping: {
      type: "standard",
      duration: "3-5 business days",
      cost: "free",
      international: {
        available: true,
        cost: "variable",
        duration: "7-15 business days",
      },
    },
    returnPolicy: {
      duration: "30 days",
      condition: "Unworn with tags, original packaging",
    },
    ratingsBreakdown: {
      5: 3200,
      4: 900,
      3: 250,
      2: 100,
      1: 70,
    },
    season: ["spring", "fall", "winter"],
    origin: "Made in Bangladesh",
    careInstructions: [
      "Machine wash cold",
      "Do not bleach",
      "Tumble dry low",
      "Warm iron if needed",
    ],
    modelWearing: {
      height: "6'1\"",
      size: "M",
    },
    fit: "slim",
    waistRise: "mid-rise",
    lengthOptions: ["30", "32", "34"],
    sustainability: {
      ecoFriendlyDyes: true,
      waterSavingTechnology: true,
      recyclablePackaging: true,
    },
    relatedProducts: [
      "Levi's Men's Graphic T-Shirt",
      "Levi's Denim Jacket",
      "Levi's Leather Belt",
    ],
    wishlistEnabled: true,
    inCart: false,
    discountPercent: 33,
    productUrl: "https://www.amazon.com/dp/B08JY3YP5G",
    brandUrl: "https://www.levi.com",
    customerQuestions: [
      {
        question: "Are these jeans true to size?",
        answer:
          "Yes, these jeans fit true to size. If you're between sizes, we recommend going up to the next size for a more comfortable fit.",
      },
      {
        question: "Can I machine wash these jeans?",
        answer:
          "Yes, these jeans are machine washable. Just follow the care instructions for the best results.",
      },
    ],
    availabilityStatus: {
      stockLevel: 320,
      restockDate: "2025-05-15",
    },
  },
  {
    id: "product-qwnbqwskjawbkjbqw3",
    img: "https://images.unsplash.com/photo-1640465978467-fa011a5dfb0a",
    title: "Levi's Women's Slim Fit Stretch Jeans",
    star: 5,
    reviews: "(4,520 reviews)",
    prevPrice: "89.99",
    newPrice: "59.99",
    company: "Levi's",
    color: "blue",
    category: "jeans",
    size: ["S", "M", "L", "XL", "XXL"],
    material: "Cotton Blend",
    gender: "men",
    style: "casual",
    availability: "in stock",
    description:
      "These Levi's Men's Slim Fit Stretch Jeans are designed for ultimate comfort and a stylish, modern look. Made from a high-quality cotton blend with a touch of elastane for added stretch, they provide the perfect balance of durability and flexibility. The classic 5-pocket design offers practicality, while the slim fit ensures a sleek silhouette. These jeans are perfect for both casual outings and more dressy occasions, making them a versatile addition to any wardrobe.",
    features: [
      "Stretchable fabric for comfort and flexibility",
      "Classic 5-pocket design for practicality",
      "Slim fit cut for a sleek, modern silhouette",
      "Machine washable for easy care",
      "Available in multiple sizes for the perfect fit",
    ],
    tags: [
      "slim fit",
      "denim",
      "casual wear",
      "trendy",
      "stretchable",
      "comfortable",
      "modern",
    ],
    sku: "LV-001-SFJ-BLU",
    shipping: {
      type: "standard",
      duration: "3-5 business days",
      cost: "free",
      international: {
        available: true,
        cost: "variable",
        duration: "7-15 business days",
      },
    },
    returnPolicy: {
      duration: "30 days",
      condition: "Unworn with tags, original packaging",
    },
    ratingsBreakdown: {
      5: 3200,
      4: 900,
      3: 250,
      2: 100,
      1: 70,
    },
    season: ["spring", "fall", "winter"],
    origin: "Made in Bangladesh",
    careInstructions: [
      "Machine wash cold",
      "Do not bleach",
      "Tumble dry low",
      "Warm iron if needed",
    ],
    modelWearing: {
      height: "6'1\"",
      size: "M",
    },
    fit: "slim",
    waistRise: "mid-rise",
    lengthOptions: ["30", "32", "34"],
    sustainability: {
      ecoFriendlyDyes: true,
      waterSavingTechnology: true,
      recyclablePackaging: true,
    },
    relatedProducts: [
      "Levi's Men's Graphic T-Shirt",
      "Levi's Denim Jacket",
      "Levi's Leather Belt",
    ],
    wishlistEnabled: true,
    inCart: false,
    discountPercent: 33,
    productUrl: "https://www.amazon.com/dp/B08JY3YP5G",
    brandUrl: "https://www.levi.com",
    customerQuestions: [
      {
        question: "Are these jeans true to size?",
        answer:
          "Yes, these jeans fit true to size. If you're between sizes, we recommend going up to the next size for a more comfortable fit.",
      },
      {
        question: "Can I machine wash these jeans?",
        answer:
          "Yes, these jeans are machine washable. Just follow the care instructions for the best results.",
      },
    ],
    availabilityStatus: {
      stockLevel: 320,
      restockDate: "2025-05-15",
    },
  },
  {
    id: "product-qwnbqwskjawbkjbqw4",
    img: "https://images.unsplash.com/photo-1640465978467-fa011a5dfb0a",
    title: "Levi's Women's Slim Fit Stretch Jeans",
    star: 5,
    reviews: "(4,520 reviews)",
    prevPrice: "89.99",
    newPrice: "59.99",
    company: "Levi's",
    color: "blue",
    category: "jeans",
    size: ["S", "M", "L", "XL", "XXL"],
    material: "Cotton Blend",
    gender: "men",
    style: "casual",
    availability: "in stock",
    description:
      "These Levi's Men's Slim Fit Stretch Jeans are designed for ultimate comfort and a stylish, modern look. Made from a high-quality cotton blend with a touch of elastane for added stretch, they provide the perfect balance of durability and flexibility. The classic 5-pocket design offers practicality, while the slim fit ensures a sleek silhouette. These jeans are perfect for both casual outings and more dressy occasions, making them a versatile addition to any wardrobe.",
    features: [
      "Stretchable fabric for comfort and flexibility",
      "Classic 5-pocket design for practicality",
      "Slim fit cut for a sleek, modern silhouette",
      "Machine washable for easy care",
      "Available in multiple sizes for the perfect fit",
    ],
    tags: [
      "slim fit",
      "denim",
      "casual wear",
      "trendy",
      "stretchable",
      "comfortable",
      "modern",
    ],
    sku: "LV-001-SFJ-BLU",
    shipping: {
      type: "standard",
      duration: "3-5 business days",
      cost: "free",
      international: {
        available: true,
        cost: "variable",
        duration: "7-15 business days",
      },
    },
    returnPolicy: {
      duration: "30 days",
      condition: "Unworn with tags, original packaging",
    },
    ratingsBreakdown: {
      5: 3200,
      4: 900,
      3: 250,
      2: 100,
      1: 70,
    },
    season: ["spring", "fall", "winter"],
    origin: "Made in Bangladesh",
    careInstructions: [
      "Machine wash cold",
      "Do not bleach",
      "Tumble dry low",
      "Warm iron if needed",
    ],
    modelWearing: {
      height: "6'1\"",
      size: "M",
    },
    fit: "slim",
    waistRise: "mid-rise",
    lengthOptions: ["30", "32", "34"],
    sustainability: {
      ecoFriendlyDyes: true,
      waterSavingTechnology: true,
      recyclablePackaging: true,
    },
    relatedProducts: [
      "Levi's Men's Graphic T-Shirt",
      "Levi's Denim Jacket",
      "Levi's Leather Belt",
    ],
    wishlistEnabled: true,
    inCart: false,
    discountPercent: 33,
    productUrl: "https://www.amazon.com/dp/B08JY3YP5G",
    brandUrl: "https://www.levi.com",
    customerQuestions: [
      {
        question: "Are these jeans true to size?",
        answer:
          "Yes, these jeans fit true to size. If you're between sizes, we recommend going up to the next size for a more comfortable fit.",
      },
      {
        question: "Can I machine wash these jeans?",
        answer:
          "Yes, these jeans are machine washable. Just follow the care instructions for the best results.",
      },
    ],
    availabilityStatus: {
      stockLevel: 320,
      restockDate: "2025-05-15",
    },
  },
  {
    id: "product-qwnbqwskjawbkjbqw5",
    img: "https://images.unsplash.com/photo-1640465978467-fa011a5dfb0a",
    title: "Levi's Women's Slim Fit Stretch Jeans",
    star: 5,
    reviews: "(4,520 reviews)",
    prevPrice: "89.99",
    newPrice: "59.99",
    company: "Levi's",
    color: "blue",
    category: "jeans",
    size: ["S", "M", "L", "XL", "XXL"],
    material: "Cotton Blend",
    gender: "men",
    style: "casual",
    availability: "in stock",
    description:
      "These Levi's Men's Slim Fit Stretch Jeans are designed for ultimate comfort and a stylish, modern look. Made from a high-quality cotton blend with a touch of elastane for added stretch, they provide the perfect balance of durability and flexibility. The classic 5-pocket design offers practicality, while the slim fit ensures a sleek silhouette. These jeans are perfect for both casual outings and more dressy occasions, making them a versatile addition to any wardrobe.",
    features: [
      "Stretchable fabric for comfort and flexibility",
      "Classic 5-pocket design for practicality",
      "Slim fit cut for a sleek, modern silhouette",
      "Machine washable for easy care",
      "Available in multiple sizes for the perfect fit",
    ],
    tags: [
      "slim fit",
      "denim",
      "casual wear",
      "trendy",
      "stretchable",
      "comfortable",
      "modern",
    ],
    sku: "LV-001-SFJ-BLU",
    shipping: {
      type: "standard",
      duration: "3-5 business days",
      cost: "free",
      international: {
        available: true,
        cost: "variable",
        duration: "7-15 business days",
      },
    },
    returnPolicy: {
      duration: "30 days",
      condition: "Unworn with tags, original packaging",
    },
    ratingsBreakdown: {
      5: 3200,
      4: 900,
      3: 250,
      2: 100,
      1: 70,
    },
    season: ["spring", "fall", "winter"],
    origin: "Made in Bangladesh",
    careInstructions: [
      "Machine wash cold",
      "Do not bleach",
      "Tumble dry low",
      "Warm iron if needed",
    ],
    modelWearing: {
      height: "6'1\"",
      size: "M",
    },
    fit: "slim",
    waistRise: "mid-rise",
    lengthOptions: ["30", "32", "34"],
    sustainability: {
      ecoFriendlyDyes: true,
      waterSavingTechnology: true,
      recyclablePackaging: true,
    },
    relatedProducts: [
      "Levi's Men's Graphic T-Shirt",
      "Levi's Denim Jacket",
      "Levi's Leather Belt",
    ],
    wishlistEnabled: true,
    inCart: false,
    discountPercent: 33,
    productUrl: "https://www.amazon.com/dp/B08JY3YP5G",
    brandUrl: "https://www.levi.com",
    customerQuestions: [
      {
        question: "Are these jeans true to size?",
        answer:
          "Yes, these jeans fit true to size. If you're between sizes, we recommend going up to the next size for a more comfortable fit.",
      },
      {
        question: "Can I machine wash these jeans?",
        answer:
          "Yes, these jeans are machine washable. Just follow the care instructions for the best results.",
      },
    ],
    availabilityStatus: {
      stockLevel: 320,
      restockDate: "2025-05-15",
    },
  },
];
export default data;
