import type { Metadata } from "next";
import { Lexend_Deca } from "next/font/google";
import "./globals.css";
import Footer from "@/components/Base/Footer";
import Header from "@/components/Base/Header";
import Providers from "./providers";
import { Toaster } from "sonner";

const lexendSans = Lexend_Deca({
  variable: "--font-lexend-sans",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${lexendSans.variable}  antialiased`}
      >
        <Providers>
          <Header />

          {children}
          <Footer />
          <Toaster />
        </Providers>
      </body>
    </html>
  );
}
